npm i -g rocambole-commafirst
npm i -g esformatter-quotes
npm i -g esformatter-braces
npm i -g esformatter-semicolons
npm i -g esformatter-dot-notation
npm i -g esformatter-literal-notation
npm i -g esformatter-parseint
npm i -g esformatter-var-each
npm i -g esformatter-eol-last
npm i -g esformatter-phonetic
npm i -g esformatter-spaced-lined-comment
npm i -g esformatter-quote-props
npm i -g esformatter-shebang-ignore
npm i -g esformatter-jsx-ignore
npm i -g esformatter-jsx
npm i -g esformatter-jquery-chain
npm i -g esformatter-special-bangs
npm i -g esformatter-collapse-objects
